window.bollywoodSongs = [
    // ==========================================
    // ❤️ ROMANTIC SONGS (T-Series Official)
    // ==========================================
    { id: "Umqb9KENgmk", title: "Tum Hi Ho", artist: "Arijit Singh", category: "romantic" },
    { id: "BBAyRZ297uk", title: "Vaaste", artist: "Dhvani Bhanushali", category: "romantic" },
    { id: "sCbbMZ-q4-g", title: "Lut Gaye", artist: "Jubin Nautiyal", category: "romantic" },
    { id: "18L-I-p-s0A", title: "Dil Galti Kar Baitha Hai", artist: "Jubin Nautiyal", category: "romantic" },
    { id: "D92x1Q2P6h0", title: "Main Rahoon Ya Na Rahoon", artist: "Armaan Malik", category: "romantic" },
    { id: "e-3-GfJ-Cvg", title: "Sanam Re", artist: "Arijit Singh", category: "romantic" },
    { id: "u8uJpM3B6jU", title: "Ik Vaari Aa", artist: "Arijit Singh", category: "romantic" },
    { id: "hE9yH8eQyO0", title: "Pal Pal Dil Ke Paas", artist: "Arijit Singh", category: "romantic" },
    { id: "U3K5M9J9KzA", title: "Thoda Thoda Pyaar", artist: "Stebin Ben", category: "romantic" },
    { id: "Jm9_b2kLgU0", title: "Nayan", artist: "Dhvani Bhanushali", category: "romantic" },
    { id: "3o55d_sQk1w", title: "Mast Nazron Se", artist: "Jubin Nautiyal", category: "romantic" },
    { id: "l4u1L8a49y4", title: "Dil Chahte Ho", artist: "Jubin Nautiyal", category: "romantic" },
    { id: "R4r25U1q-1w", title: "Taaron Ke Shehar", artist: "Neha Kakkar & Jubin", category: "romantic" },
    { id: "B41N4Y5g4U0", title: "Is Qadar", artist: "Darshan Raval & Tulsi", category: "romantic" },
    { id: "2L3M44sQG00", title: "Khushi Jab Bhi Teri", artist: "Jubin Nautiyal", category: "romantic" },
    { id: "b122wP5gU1w", title: "Barsaat Ki Dhun", artist: "Jubin Nautiyal", category: "romantic" },
    { id: "gvyUuxdRdR4", title: "Raataan Lambiyan", artist: "Jubin Nautiyal", category: "romantic" },
    { id: "381d6pM_R_s", title: "Ghar Se Nikalte Hi", artist: "Armaan Malik", category: "romantic" },
    { id: "3m9P4UfP3Ww", title: "Enna Sona", artist: "Arijit Singh", category: "romantic" },
    { id: "0aP2jS3aG14", title: "Soch Na Sake", artist: "Arijit Singh", category: "romantic" },
    { id: "h03N3L41j10", title: "High Rated Gabru", artist: "Guru Randhawa", category: "romantic" },
    { id: "N4Z6M732z3E", title: "Lahore", artist: "Guru Randhawa", category: "romantic" },
    { id: "1w5OqS124uE", title: "Ban Ja Rani", artist: "Guru Randhawa", category: "romantic" },
    { id: "d1pL2wP5YqA", title: "Made In India", artist: "Guru Randhawa", category: "romantic" },
    { id: "J29-9eW2Y70", title: "Chogada", artist: "Darshan Raval", category: "romantic" },
    { id: "II2EO3Nw4m0", title: "Kamariya", artist: "Darshan Raval", category: "romantic" },
    { id: "K1a2L-4J1pA", title: "Baby Girl", artist: "Guru Randhawa", category: "romantic" },
    { id: "AEIVhBSMDWM", title: "Gerua", artist: "Arijit Singh", category: "romantic" },
    { id: "SAcpESN_Fk4", title: "Dil Diyan Gallan", artist: "Atif Aslam", category: "romantic" },
    { id: "DK_UsATwoxI", title: "Nazm Nazm", artist: "Arko", category: "romantic" },
    { id: "VjN4yXh7A70", title: "Tum Se Hi", artist: "Mohit Chauhan", category: "romantic" },
    { id: "T94PHkuydcw", title: "Kun Faya Kun", artist: "A.R. Rahman", category: "romantic" },
    { id: "8d_C6aE9-88", title: "Humsafar", artist: "Akhil Sachdeva", category: "romantic" },
    { id: "hhdSyqTCscA", title: "Zaalima", artist: "Arijit Singh", category: "romantic" },
    { id: "cUM6D81uS18", title: "Hawaayein", artist: "Arijit Singh", category: "romantic" },
    { id: "k3g_WjL10y4", title: "Kalank Title Track", artist: "Arijit Singh", category: "romantic" },
    { id: "E1pM-J7X07M", title: "Tera Yaar Hoon Main", artist: "Arijit Singh", category: "romantic" },
    { id: "0WtRNGubWnA", title: "Balam Pichkari", artist: "Vishal Dadlani", category: "romantic" },
    { id: "yIIGQB6EMAM", title: "Bom Diggy Diggy", artist: "Zack Knight", category: "romantic" },
    { id: "139wM_x18n0", title: "Dil Chori", artist: "Honey Singh", category: "romantic" },
    { id: "hW4010aJ7Y8", title: "Chhote Chhote Peg", artist: "Honey Singh", category: "romantic" },
    { id: "mNuhKUOD_A0", title: "Deva Deva", artist: "Arijit Singh", category: "romantic" },
    { id: "vhJ2wT-_wvg", title: "Tere Pyaar Mein", artist: "Arijit Singh", category: "romantic" },
    { id: "RLzC55ai0eo", title: "Heeriye", artist: "Jasleen Royal & Arijit", category: "romantic" },
    { id: "N7c00vJzRj4", title: "Ve Kamleya", artist: "Arijit Singh", category: "romantic" },
    { id: "8sLS2knUa6c", title: "Phir Aur Kya Chahiye", artist: "Arijit Singh", category: "romantic" },
    { id: "9Q8_JcZq5iU", title: "Tere Vaaste", artist: "Varun Jain", category: "romantic" },
    { id: "87JIOAX3Sub", title: "What Jhumka?", artist: "Arijit Singh", category: "romantic" },
    { id: "h1e5a5nQ154", title: "Tauba Tauba", artist: "Karan Aujla", category: "romantic" },

    // ==========================================
    // 💔 SAD SONGS (T-Series Official)
    // ==========================================
    { id: "PVxc5fH9ZVw", title: "Pachtaoge", artist: "Arijit Singh", category: "sad" },
    { id: "68B6E-pM8gU", title: "Bedardi Se Pyaar Ka", artist: "Jubin Nautiyal", category: "sad" },
    { id: "eR58D2034t8", title: "Wafa Na Raas Aayee", artist: "Jubin Nautiyal", category: "sad" },
    { id: "8-E4J6bT4jA", title: "Phir Mohabbat", artist: "Arijit Singh", category: "sad" },
    { id: "83_6Jj2389o", title: "Hamari Adhuri Kahani", artist: "Arijit Singh", category: "sad" },
    { id: "e4d7-o-o_3A", title: "Humnava Mere", artist: "Jubin Nautiyal", category: "sad" },
    { id: "2lB5sJ0N55M", title: "Rula Ke Gaya Ishq", artist: "Stebin Ben", category: "sad" },
    { id: "43fS4bM0vLw", title: "Phir Bhi Tumko Chaahunga", artist: "Arijit Singh", category: "sad" },
    { id: "3M1vO2mG2U0", title: "Lo Maaf Kiya", artist: "Arijit Singh", category: "sad" },
    { id: "R27P1y-G39o", title: "Bhula Dunga", artist: "Darshan Raval", category: "sad" },
    { id: "m8oB3-3U-p8", title: "Ek Tarfa", artist: "Darshan Raval", category: "sad" },
    { id: "08P13W6d_q8", title: "Dil Tod Ke", artist: "B Praak", category: "sad" },
    { id: "wF_B_aB3X1A", title: "Teri Mitti", artist: "B Praak", category: "sad" },
    { id: "sM3N4Q_L1kU", title: "Roke Na Ruke Naina", artist: "Arijit Singh", category: "sad" },
    { id: "284Ov7ysmfA", title: "Channa Mereya", artist: "Arijit Singh", category: "sad" },
    { id: "sK7riqg2mr4", title: "Agar Tum Saath Ho", artist: "Arijit Singh", category: "sad" },
    { id: "dTUuN3j2RkY", title: "Tujhe Kitna Chahne Lage", artist: "Arijit Singh", category: "sad" },
    { id: "VOLKJJvfCgA", title: "Bekhayali", artist: "Sachet Tandon", category: "sad" },
    { id: "v_43p4mJ5Y4", title: "Jaan Nisaar", artist: "Arijit Singh", category: "sad" },
    { id: "atVof3pjT-I", title: "Kaun Tujhe", artist: "Palak Muchhal", category: "sad" },
    { id: "3wP8s8U5Y4A", title: "Lo Safar", artist: "Jubin Nautiyal", category: "sad" },
    { id: "420Nsc-F-F4", title: "Sunn Raha Hai Na Tu", artist: "Ankit Tiwari", category: "sad" },
    { id: "a8A7sJ1vG00", title: "Galliyan", artist: "Ankit Tiwari", category: "sad" },
    { id: "W4dM46U7o14", title: "Banjaara", artist: "Mohammed Irfan", category: "sad" },
    { id: "hJ3N_eP1Gso", title: "Baarishein", artist: "Atif Aslam", category: "sad" },
    { id: "y4S1u9pW1g4", title: "Dillagi", artist: "Rahat Fateh Ali Khan", category: "sad" },
    { id: "6-n_szx2XRE", title: "Zaroori Tha", artist: "Rahat Fateh Ali Khan", category: "sad" },
    { id: "2E_3uXoZlJ8", title: "O Bedardeya", artist: "Arijit Singh", category: "sad" },
    { id: "caT-H0T4k8M", title: "Satranga", artist: "Arijit Singh", category: "sad" },
    { id: "iAib15a77hM", title: "Pehle Bhi Main", artist: "Vishal Mishra", category: "sad" },
    { id: "_f41j3L-4qU", title: "Tainu Khabar Nahi", artist: "Arijit Singh", category: "sad" }
];
