const songsList = [
    { title: "Tujhe Dekha Toh", artist: "Kumar Sanu, Lata Mangeshkar", id: "cNV5hLSa9D8" },
    { title: "Pehla Nasha", artist: "Udit Narayan, Sadhana Sargam", id: "1Gup5_F9M7Y" },
    { title: "Chura Ke Dil Mera", artist: "Kumar Sanu, Alka Yagnik", id: "H26Y3c-70vg" },
    { title: "Mera Dil Bhi Kitna Pagal Hai", artist: "Kumar Sanu, Alka Yagnik", id: "-d0b_M_8F4s" },
    { title: "Dheere Dheere Se Meri Zindagi", artist: "Kumar Sanu", id: "X_590lq7x50" },
    { title: "Dil Hai Ke Manta Nahin", artist: "Kumar Sanu, Anuradha Paudwal", id: "N2s74Vd5h-4" },
    { title: "Bahut Pyar Karte Hain", artist: "Anuradha Paudwal", id: "_N4R4D5g-3g" },
    { title: "Tip Tip Barsa Phani", artist: "Udit Narayan, Alka Yagnik", id: "_u4bBqN5f30" },
    { title: "Sochenge Tumhe Pyaar", artist: "Kumar Sanu", id: "Y8bX8o3g520" },
    { title: "Jeeta Tha Jiske Liye", artist: "Kumar Sanu, Alka Yagnik", id: "x0vQ8nF5KjE" },
    { title: "Aaye Ho Meri Zindagi Mein", artist: "Udit Narayan", id: "8W1K8yH5j4Q" },
    { title: "Pardesi Pardesi Jana Nahi", artist: "Udit Narayan, Alka Yagnik", id: "p0H8F5g-2j4" },
    { title: "Kitna Pyaara Tujhe Rab Ne", artist: "Udit Narayan, Alka Yagnik", id: "vH7f-9k3L4Q" },
    { title: "Tumse Milne Ki Tamanna Hai", artist: "S.P. Balasubrahmanyam", id: "n8B7v5g-3k4" },
    { title: "Pehli Pehli Baar Mohabbat Ki Hai", artist: "Kumar Sanu, Alka Yagnik", id: "m7F4v8g-2j9" },
    { title: "Ek Ladki Ko Dekha Toh Aisa Laga", artist: "Kumar Sanu", id: "k7F8v5g-9j2" },
    { title: "Rooth Na Jana Tumse Kaho Toh", artist: "Kumar Sanu", id: "j8F5v2g-4k9" },
    { title: "Do Dil Mil Rahe Hain", artist: "Kumar Sanu", id: "x8F9v2g-5k1" },
    { title: "Ho Gaya Hai Tujhko Toh Pyar", artist: "Udit Narayan, Lata Mangeshkar", id: "v8F7v2g-6k4" },
    { title: "Mehndi Laga Ke Rakhna", artist: "Udit Narayan, Lata Mangeshkar", id: "p8F5v2g-7k3" },
    { title: "Kuch Kuch Hota Hai", artist: "Udit Narayan, Alka Yagnik", id: "t8F4v2g-8k2" },
    { title: "Ladki Badi Anjani Hai", artist: "Kumar Sanu, Alka Yagnik", id: "g8F2v2g-9k5" },
    { title: "Koi Mil Gaya", artist: "Udit Narayan, Alka Yagnik", id: "b8F1v2g-1k6" },
    { title: "Tujhe Yaad Na Meri Aayee", artist: "Alka Yagnik, Manpreet Akhtar", id: "c8F9v2g-2k7" },
    { title: "Suraj Hua Roshan", artist: "Sonu Nigam, Alka Yagnik", id: "u8F8v2g-3k8" },
    { title: "Kabhi Khushi Kabhie Gham", artist: "Lata Mangeshkar", id: "h8F7v2g-4k9" },
    { title: "You Are My Soniya", artist: "Sonu Nigam, Alka Yagnik", id: "y8F6v2g-5k0" },
    { title: "Bole Chudiyan", artist: "Amit Kumar, Sonu Nigam, Alka Yagnik", id: "x8F5v2g-6k1" },
    { title: "Tum Dil Ki Dhadkan Mein", artist: "Abhijeet, Alka Yagnik", id: "w8F4v2g-7k2" },
    { title: "Dil Ne Yeh Kaha Hai Dil Se", artist: "Udit Narayan, Alka Yagnik", id: "z8F3v2g-8k3" },
    { title: "Na Tum Jaano Na Hum", artist: "Lucky Ali", id: "q8F2v2g-9k4" },
    { title: "Kaho Naa Pyaar Hai", artist: "Udit Narayan, Alka Yagnik", id: "a8F1v2g-0k5" },
    { title: "Ek Pal Ka Jeena", artist: "Lucky Ali", id: "e8F0v2g-1k6" },
    { title: "Chand Chupa Badal Mein", artist: "Udit Narayan, Alka Yagnik", id: "d8F9v1g-2k7" },
    { title: "Aankhon Ki Gustakhiyan", artist: "Kumar Sanu, Kavita Krishnamurthy", id: "s8F8v1g-3k8" },
    { title: "Hum Dil De Chuke Sanam", artist: "Kavita Krishnamurthy, Udit Narayan", id: "f8F7v1g-4k9" },
    { title: "Tadap Tadap Ke", artist: "KK, Dominique Cerejo", id: "t8F6v1g-5k0" },
    { title: "Nimbooda Nimbooda", artist: "Kavita Krishnamurthy, Karsan Sargathia", id: "n8F5v1g-6k1" },
    { title: "Taal Se Taal Mila", artist: "Alka Yagnik, Udit Narayan", id: "m8F4v1g-7k2" },
    { title: "Ishq Bina Kya Jeena Yaaro", artist: "Sujatha, Sonu Nigam, A.R. Rahman", id: "i8F3v1g-8k3" },
    { title: "Nahin Samne Tu", artist: "Hariharan, Sukhwinder Singh", id: "r8F2v1g-9k4" },
    { title: "Ramta Jogi", artist: "Sukhwinder Singh, Alka Yagnik", id: "k8F1v1g-0k5" },
    { title: "Kahin Deep Jale Kahin Dil", artist: "Lata Mangeshkar", id: "o8F0v1g-1k6" },
    { title: "Awaara Paagal Deewana", artist: "Shaan, Sunidhi Chauhan", id: "p8F9v0g-2k7" },
    { title: "Baazigar O Baazigar", artist: "Kumar Sanu, Alka Yagnik", id: "l8F8v0g-3k8" },
    { title: "Yeh Kaali Kaali Aankhen", artist: "Kumar Sanu, Anu Malik", id: "v8F7v0g-4k9" },
    { title: "Jaati Hoon Main", artist: "Kumar Sanu, Alka Yagnik", id: "j8F6v0g-5k0" },
    { title: "Rana Ji Maaf Karna", artist: "Alka Yagnik, Ila Arun", id: "r8F5v0g-6k1" },
    { title: "Ghar Se Nikalte Hi", artist: "Udit Narayan", id: "g8F4v0g-7k2" },
    { title: "Aisi Deewangi Dekhi Nahi Kahi", artist: "Alka Yagnik, Vinod Rathod", id: "a8F3v0g-8k3" }
];
